### ISSUE TITLE
Hekp to Create

### ISSUE THREAD

**Issue by Rogerio4801** [xlat/pbjson#5]
Hello, how can I create json with several items inside an array.

{
    "cooperative": 1090,
    "templateName": "BankStatement",
    "templateProps": {
        "list": [
            {
                "date": "2023-05-02",
                "description": "PIX Lorem ipsum dolor sit amet",
                "amount": -100
            },
            {
                "date": "2024-01-01",
                "description": "Fatura Cartão Lorem ipsum dolor sit amet",
                "amount": 200
            },
            {
                "date": "2024-01-01",
                "description": "Saldo do dia",
                "amount": 0
            }
        ],
        "user": {
            "username": "Fulano da Silva",
            "accountNumber": "619132",
            "emissionDate": "2024-04-25T11:22:05.354823",
            "period": "7 dias"
        }
    }
}

I need to write a structure like the example, thank you in advance for your help.

**Comment by abdurahman14** [comment]
Hi,

just pushed fixes, improvements and sample mathing your given object.

**Comment by xlat** [comment]
@abdurahman14 yep 👍

**Comment by Rogerio4801** [comment]
Thank you for your support.
